title: Template # Learning Lab course
tagline: Template for new lab courses # Description for your course, displayed on the course catalog
description: Description # Longer description for course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is created for each individual learner

template:
  name: example-course # the name of the repository when it is created for the learner
  repo: learninglab-template # the name of the repository to be copied, must have the same owner as the course. If omitted, the learner's repository will be empty.
  description: Description # (OPTIONAL) A one-line description which will be set for the GitHub repository.

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo
# You can execute multiple actions in the `before` block. Refer to https://lab.github.com/docs/before-block
# Some actions require additional options as the one shown below, those options should appear below `type:`
# Below are example actions, full list at https://lab.github.com/docs/actions/
before:
- type: updateBranchProtection # Protects the master branch 
- type: createIssue
  title: Getting started with NanoMFG
  body: 01_NanoMFG.md
  
# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: INTERNAL COMMENT DESCRIBING STEP 
- title: Close an issue # the title of the step, shown to the learner in the course progress page
  description: Example step for course # a description of the step, shown to the learner in the course progress page
  event: issues.closed # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  link: '{{ repoUrl }}/issues/1' 
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: createPullRequest
    title: example-action
    head: example-action
    body: example-pull.md

# Step 2: INTERNAL COMMENT FOR STEP 2
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 3: INTERNAL COMMENT FOR STEP 3
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 4: INTERNAL COMMENT FOR STEP 4
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 5: INTERNAL COMMENT FOR STEP 5
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 6: INTERNAL COMMENT FOR STEP 6
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 7: INTERNAL COMMENT FOR STEP 7
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 8: INTERNAL COMMENT FOR STEP 8
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 9: INTERNAL COMMENT FOR STEP 9
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Step 10: INTERNAL COMMENT FOR STEP 10
# - title: 
#  description: 
#  event: 
#  actions: 
#  - type: 

# Add additional steps below
